services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  php-fpm:
    container_name: php-fpm
    image: sysafarila/php-laravel:8.1-fpm-alpine
    volumes:
      - ./laravel:/var/www/html
    restart: always
  mariadb:
    image: mariadb:10.10
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=backend
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: always
