services:
  nginx:
    image: nginx:stable-alpine-slim
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - laravel_data:/laravel:ro
    restart: always
  php-fpm:
    image: sysafarila/php-laravel:8.3-fpm-alpine
    volumes:
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
      - laravel_data:/laravel:rw
    restart: always
    depends_on:
      - mariadb
      - nginx
  mariadb:
    image: mariadb:10.10
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=backend
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  # postgres17:
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=leeasy_rafindo
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data:rw
  #   restart: always

volumes:
  laravel_data:
  mariadb_data:
  postgres_data:
